buildpack:
  name: Blazar-Buildpack-Java

env:
  SKIP_VERSION_OVERRIDE_ON_BRANCH: 2.16-hubspot
  MAVEN_DEPLOY_ARGS: -DskipNexusStagingDeployMojo=true


stepActivation:
  notify:
    branches: [2.16-hubspot]

