buildpack:
  name: Blazar-Buildpack-Java

env:
  SKIP_VERSION_OVERRIDE_ON_BRANCH: 2.12-hubspot
#  MAVEN_ARGS: -DskipTests -Drat.skip=true -Dspotless.check.skip=true


stepActivation:
  notify:
    branches: [2.12-hubspot]

